parameters:
#    msi_gallery.example.class: Msi\GalleryBundle\Example

services:
#    msi_gallery.example:
#        class: %msi_gallery.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
