admin_gallery_image:
  pattern:  /
  defaults: { _controller: MsiGalleryBundle:admin\GalleryImage:index }

admin_gallery_image_batch:
  pattern:  /batch/
  defaults: { _controller: MsiGalleryBundle:admin\GalleryImage:batch }

admin_gallery_image_new:
  pattern:  /new/
  defaults: { _controller: MsiGalleryBundle:admin\GalleryImage:new }

admin_gallery_image_create:
  pattern:  /create/
  defaults: { _controller: MsiGalleryBundle:admin\GalleryImage:create }
    
admin_gallery_image_edit:
  pattern:  /{id}/edit/
  defaults: { _controller: MsiGalleryBundle:admin\GalleryImage:edit }
  requirements:
    id: \d+

admin_gallery_image_update:
  pattern:  /{id}/update/
  defaults: { _controller: MsiGalleryBundle:admin\GalleryImage:update }
  requirements:
    id: \d+