admin_gallery:
  pattern:  /
  defaults: { _controller: MsiGalleryBundle:admin\Gallery:index }

admin_gallery_batch:
  pattern:  /batch/
  defaults: { _controller: MsiGalleryBundle:admin\Gallery:batch }

admin_gallery_new:
  pattern:  /new/
  defaults: { _controller: MsiGalleryBundle:admin\Gallery:new }

admin_gallery_create:
  pattern:  /create/
  defaults: { _controller: MsiGalleryBundle:admin\Gallery:create }
    
admin_gallery_edit:
  pattern:  /{id}/edit/
  defaults: { _controller: MsiGalleryBundle:admin\Gallery:edit }
  requirements:
    id: \d+

admin_gallery_update:
  pattern:  /{id}/update/
  defaults: { _controller: MsiGalleryBundle:admin\Gallery:update }
  requirements:
    id: \d+