gallery_image:
  pattern:  /
  defaults: { _controller: MsiGalleryBundle:admin\GalleryImage:index }

gallery_image_batch:
  pattern:  /batch/
  defaults: { _controller: MsiGalleryBundle:admin\GalleryImage:batch }

gallery_image_new:
  pattern:  /new/
  defaults: { _controller: MsiGalleryBundle:admin\GalleryImage:new }

gallery_image_create:
  pattern:  /create/
  defaults: { _controller: MsiGalleryBundle:admin\GalleryImage:create }
    
gallery_image_edit:
  pattern:  /{id}/edit/
  defaults: { _controller: MsiGalleryBundle:admin\GalleryImage:edit }
  requirements:
    id: \d+

gallery_image_update:
  pattern:  /{id}/update/
  defaults: { _controller: MsiGalleryBundle:admin\GalleryImage:update }
  requirements:
    id: \d+